#!/bin/bash

git pull &&
npm i
(cd ./server && npm i)
((cd ../swiss-army-knife && git pull) || (cd ../ && git clone https://github.com/fatlard1993/swiss-army-knife.git)) &&
(cd ../swiss-army-knife && ./SETUP)
gulp compile
mkdir -p ./client/public &&
(cd ./client/public && [[ ! -e ./fonts ]] && ln -sT ../../../swiss-army-knife/client/fonts fonts)
(cd ./client/public && [[ ! -e ./assets ]] && ln -sT ../assets assets)